notes_env/notes_web/notees/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('inicio/', views.pagina_inicio, name='pagina_inicio'),
    path('login/', views.inicio_sesion, name='login'),
    path('registro/', views.registro, name='registro'),
    path('lista_notas/', views.lista_notas, name='lista_notas'),
    path('crear/', views.crear_nota, name='creanota'),
    path('editar/<int:nota_id>/', views.editar_nota, name='editar_nota'),
    path('borrar/<int:nota_id>/', views.borrar_nota, name='borrar_nota'),
    path('nota/<int:nota_id>/', views.detalle_nota, name='detalle_nota'),
]

'''
path('lo que aparece en la url al buscar', a lo que redirigimos (métodos), ...)
'''

notes_env/notes_web/notes_web/urls.py
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('', include('notees.urls')),
    path('notas/', include('notees.urls')),
   # path('admin/', admin.site.urls),
]

notes_env/notes_web/notees/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Nota(models.Model):
    titulo = models.CharField(max_length=100)
    contenido = models.TextField()
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

notes_env/notes_web/notees/forms.py
from django import forms
from .models import Nota

class NotaForm(forms.ModelForm):
    class Meta:
        model = Nota
        fields = ['titulo', 'contenido']

notes_env/notes_web/notees/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Nota
from .forms import NotaForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
import time
from django.contrib.auth.models import User

# Create your views here.
from django.http import HttpResponse


def inicio(request):
    return redirect('pagina_inicio')  # Redirige a la página de inicio deseada

def pagina_inicio(request):
    return render(request, 'pagina_inicio.html')

def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('lista_notas')
        else:
            messages.error(request, 'Contraseña no válida. Por favor, inténtelo de nuevo.')
    else:
        form = UserCreationForm()
    return render(request, 'registro.html', {'form': form})


def inicio_sesion(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('lista_notas')
        else:
            messages.error(request, 'Usuario o contraseña incorrectos. Por favor, inténtelo de nuevo.')  # Añade un mensaje de error
    else:
        form = AuthenticationForm()
    return render(request, 'inicio_sesion.html', {'form': form})

def cerrar_sesion(request):
    logout(request)
    return redirect('login')

@login_required(login_url=reverse_lazy("login"))
def lista_notas(request):
    notas = Nota.objects.all().order_by('-fecha_actualizacion')
    return render(request, 'lista_notas.html', {'notas': notas})

@login_required(login_url=reverse_lazy("login"))
def crear_nota(request):
    if request.method == 'POST':
        form = NotaForm(request.POST)
        if form.is_valid():
            # Obtener el usuario actual
            creador = request.user
            # Asignar el usuario actual como creador de la nota
            nota = form.save(commit=False)
            nota.creador = request.user  # Asignar el usuario autenticado como creador de la nota
            nota.save()
            return redirect('lista_notas')
    else:
        form = NotaForm()
    return render(request, 'crear_nota.html', {'form': form})

@login_required(login_url=reverse_lazy("login"))
def borrar_nota(request, nota_id):
    nota = get_object_or_404(Nota, pk=nota_id)
    nota.delete()
    return redirect('lista_notas')

@login_required(login_url=reverse_lazy("login"))
def editar_nota(request, nota_id):
    nota = get_object_or_404(Nota, pk=nota_id)
    if request.method == 'POST':
        form = NotaForm(request.POST, instance=nota)
        if form.is_valid():
            nota.save()
            return redirect('lista_notas')
    else:
        form = NotaForm(instance=nota)
    return render(request, 'editar_nota.html', {'form': form, 'nota': nota})

@login_required(login_url=reverse_lazy("login"))
def detalle_nota(request, nota_id):
    nota = get_object_or_404(Nota, pk=nota_id)
    return render(request, 'detalle_nota.html', {'nota': nota})

notes_env/notes_web/notees/templates/crear_nota.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">
<link rel="stylesheet" href="../../static/crear_nota.css">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nota</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>
   <label for="id_titulo"></label>
   <input class="titulo" type="text" name="titulo" maxlength="100" required id="id_titulo" placeholder="Encabezado...">
 </p>
 <p>
   <label for="id_contenido"></label>
   <textarea name="contenido" cols="40" rows="10" required id="id_contenido" placeholder="Comienza a escribir aquí...">
</textarea>
 </p>

        <button type="submit">Guardar</button>
        <a id="cancelar" href="{% url 'lista_notas' %}">Cancelar</a>
    </form>
</body>
</html>

notes_env/notes_web/notees/templates/detalle_nota.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">
<link rel="stylesheet" href="../../../static/detalle_nota.css">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle</title>

</head>
<body>
    <h1>{{ nota.titulo }}</h1>
    <p id="contenido">{{ nota.contenido }}</p>
    <!-- <p>Creador: {{ nota.creador.username }}</p> -->
    <!-- <p>Fecha de Creación: {{ nota.fecha_creacion }}</p> -->
    <p>{{ nota.fecha_actualizacion }}</p>
</body>
</html>

notes_env/notes_web/notees/templates/editar_nota.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">
<link rel="stylesheet" href="../../../static/editar_nota.css">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nota</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <p>
   <label for="id_titulo"></label>
   <input class="titulo" type="text" name="titulo" maxlength="100" required id="id_titulo" value="{{ nota.titulo }}">
 </p>
 <p>
   <label for="id_contenido"></label>
   <textarea name="contenido" cols="40" rows="10" required id="id_contenido">{{ nota.contenido }}
</textarea>
 </p>
        <input type="hidden" name="id" value="{{ nota.id }}"> <!-- Campo oculto para el ID de la nota -->
        <!-- HE comprobado que no hace falta escribir esto del hidden id
        para que funcione-->
        <button type="submit">Guardar</button>
        <a id="cancelar" href="{% url 'lista_notas' %}">Cancelar</a>
    </form>
</body>
</html>

notes_env/notes_web/notees/templates/inicio_sesion.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">
<link rel="stylesheet" href="../../static/inicio_sesion.css">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de Sesión</title>
</head>
<body>
    <h1>Inicia Sesión</h1>
    {% if messages %}
        {% for message in messages %}
            <p id="mensaje">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <!--Este token es una medida de seguridad que protege contra ataques CSRF al asegurarse de que la solicitud proviene del usuario que inició sesión y no de un sitio web malicioso. -->
        <div class="form-group">
            <label for="id_username">Usuario:</label>
            <input type="text" id="id_username" name="username" class="form-control">
        </div>
        <div class="form-group">
            <label for="id_password">Contraseña:</label>
            <input type="password" id="id_password" name="password" class="form-control">
        </div>

            <!-- {{ form.as_p }} -->
            <!-- Esto renderiza los campos del formulario utilizando el formato de parágrafos (<p>) por defecto. -->
        <button type="submit">Iniciar Sesión</button>
    </form>
    <script>
        // Función para ocultar el mensaje de error después de 5 segundos
        setTimeout(function() {
            var errorMessage = document.getElementById('error-message');
            if (errorMessage) {
                errorMessage.style.display = 'none';
            }
        }, 5000); // 5 segundos en milisegundos
    </script>

    <p>¿Aún no tienes cuenta? <a id="cancelar" href="{% url 'registro' %}">Regístrate aquí</a></p>
</body>
</html>

notes_env/notes_web/notees/templates/lista_notas.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">

<link rel="stylesheet" href="../../static/lista_notas.css">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Notas</title>
</head>
<body style="background-image: url('/fondo.png');">
    <h1>Mis Notas</h1>
    <div id="noota">
        <a href="{% url 'creanota' %}" class="button-link">Nueva Nota</a>
    </div>
        {% for nota in notas %}
            <div id="nota">
                <a href="{% url 'detalle_nota' nota.id %}" class="detalle_nota">
                    <p>{{ nota.titulo }}</p>
                    <p id="fecha_act"> {{ nota.fecha_actualizacion }}</p>
                    </a>
                <div>
                    <a href="{% url 'editar_nota' nota.id %}" class="button-link_2">Editar</a>
                    <form id="borrar-form-{{ nota.id }}" method="post" action="{% url 'borrar_nota' nota.id %}" style="display:inline;">
                        {% csrf_token %}
                        <button class="button_borrar" type="button" onclick="mostrarConfirmacion({{ nota.id }})">Borrar</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        <p id="final"></p>

    <div id="mensaje-confirmacion" class="mensaje-confirmacion">
        <p>¿Estás seguro de que deseas borrar esta nota?</p>
        <button class="button" onclick="confirmarBorrado()">Sí</button>
        <button class="button" onclick="ocultarConfirmacion()">Cancelar</button>
    </div>

    <script>
        function mostrarConfirmacion(notaId) {
            var mensaje = document.getElementById('mensaje-confirmacion');
            mensaje.dataset.notaId = notaId;
            mensaje.classList.add('visible'); // Agregar la clase "visible" al mensaje de confirmación
            // Agregar un evento click a toda la página para ocultar el mensaje de confirmación si se hace clic en cualquier lugar fuera del botón de borrar
            document.addEventListener('click', ocultarConfirmacionFueraDeBorrar);
        }

        function ocultarConfirmacion() {
            var mensaje = document.getElementById('mensaje-confirmacion');
            mensaje.classList.remove('visible'); // Eliminar la clase "visible" del mensaje de confirmación
            // Remover el evento click de la página para evitar que se oculte el mensaje cuando se haga clic en cualquier lugar fuera del botón de borrar
            document.removeEventListener('click', ocultarConfirmacionFueraDeBorrar);
        }

        function ocultarConfirmacionFueraDeBorrar(event) {
            // Verificar si el clic ocurrió fuera del botón de borrar y del mensaje de confirmación
            var esBotonBorrar = event.target.tagName === 'BUTTON' && event.target.parentNode.tagName === 'FORM';
            var esMensajeConfirmacion = event.target.id === 'mensaje-confirmacion';
            if (!esBotonBorrar && !esMensajeConfirmacion) {
                ocultarConfirmacion();
            }
        }

        function confirmarBorrado() {
            var mensaje = document.getElementById('mensaje-confirmacion');
            var notaId = mensaje.dataset.notaId;
            document.getElementById('borrar-form-' + notaId).submit();
        }
    </script>
</body>
</html>

notes_env/notes_web/notees/templates/pagina_inicio.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notees</title>
    <link rel="stylesheet" href="../../static/styles.css">
</head>
<body>
    <h1>Bienvenido a NOTEES</h1>
    <p>Tu propio estudio de creación de notas</p>
    <a href="{% url 'login' %}">Iniciar Sesión</a>
    <a href="{% url 'registro' %}">Registrarse</a>
</body>
</html>

<!-- <link rel="stylesheet" href="../../static/detalle_nota.css"> -->

notes_env/notes_web/notees/templates/registro.html
<!DOCTYPE html>
<html lang="es" style="background-image: url('/static/fondo.png');">
<link rel="stylesheet" href="../../static/registro.css">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Regístro</title>
</head>
<body>
    <h1>Regístrate</h1>
    <form method="post">
        {% csrf_token %}

        <p>
            <label class="texto" for="id_username">Usuario:</label>
            <input class="form-control" type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required aria-describedby="id_username_helptext" id="id_username">

            <span class="helptext" id="id_username_helptext"><p>Debe incluir letras, dígitos y un caracter especial (@/./+/-/_).</p><p>Máx. 150 caracteres, mín. 8.</p>

            </span>
            <div><span class="helptext" ></span></div>
              <!-- <p class="helptext">Debe incluir letras, dígitos y un caracter especial (@/./+/-/_)</p> -->
            <span>
                 <ul>
                     <!--<li class="helptext">Your password can’t be too similar to your other personal information.</li>-->
                     <!--   <li class="helptext">Your password can’t be entirely numeric.</li>
                     Your password can’t be a commonly used password.-->
                 </ul>
            </span>
        </p>


        <p>
            <label class="texto" for="id_password1">Contraseña:</label>
            <input class="form-control" type="password" name="password1" autocomplete="new-password" required aria-describedby="id_password1_helptext" id="id_password1">
        </p>

        <div id="verif"><span class="helptext" id="id_password2_helptext">Introduzca su contraseña de nuevo para su verificación.</span></div>

        <p>
            <label class="texto" for="id_password2">Contraseña:</label>
            <input class="form-control" type="password" name="password2" autocomplete="new-password" required aria-describedby="id_password2_helptext" id="id_password2">
        </p>

            <div class="boton"><button type="submit">Registrarse</button></div>
    </form>
    <p class="color">¿Ya tienes una cuenta? <a id="cancelar" href="{% url 'login' %}">Inicia sesión aquí</a></p>
</body>
</html>